# Generated by Django 4.0 on 2023-03-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_recipe_chef'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE user_recipe DROP COLUMN cooking_instructions;")
        
    ]
