# Generated by Django 4.0 on 2023-03-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230328_0309'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE user_recipe DROP COLUMN ingredients;")
    ]
