# Generated by Django 4.0 on 2023-03-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_follower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name_plural': 'Followers'},
        ),
    ]
