# Generated by Django 4.0 on 2023-03-28 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230329_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
