# Generated by Django 4.0 on 2023-03-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_instructions',
            field=models.TextField(default='add instructions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='add ingredients'),
            preserve_default=False,
        ),
    ]
