# Generated by Django 4.1.5 on 2023-04-14 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_recipe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protein', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrates', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='user.ingredient'),
        ),
    ]
